export let filterTemplate = {
  delivery_time: [],
  certificate: [],
  shape: [],
  carat_range: {},
  color: [],
  clarity: [],
  cut: [],
  polish: [],
  symmetry: [],
  fluorescence: [],
  fluorescence_color: [],
  eye_clean: [],
  show_only_image: false,
  show_only_video: false,
  show_only_returnable: false,
  show_only_immediate_purchase: false,
  with_unknown_eye_clean: false,
  with_unknown_shade: false,
  with_unknown_luster: false,
  no_bgm: false,
  id: "",
  cert_id: "",
};
