export let filterTemplate = {
  delivery_time: [],
  certificate: [],
  shape: [],
  carat_range: {},
  color: [],
  clarity: [],
  cut: [],
  polish: [],
  symmetry: [],
  fluorescence: [],
  fluorescence_color: [],
  eye_clean: [],
  show_only_image: false,
  show_only_video: false,
  show_only_returnable: false,
  show_only_immediate_purchase: false,
  with_unknown_eye_clean: false,
  with_unknown_shade: false,
  with_unknown_luster: false,
  no_bgm: false,
  stock_id: "",
  cert_id: "",
  price_sort: "",
  type: 1,
};

export let filterTemplateMelee = {
  delivery_time: [],
  certificate: [],
  shape: [],
  carat: [],
  color: [],
  clarity: [],
  cut: [],
  polish: [],
  symmetry: [],
  fluorescence: [],
  fluorescence_color: [],
  eye_clean: [],
  show_only_image: false,
  show_only_video: false,
  show_only_returnable: false,
  show_only_immediate_purchase: false,
  with_unknown_eye_clean: false,
  with_unknown_shade: false,
  with_unknown_luster: false,
  no_bgm: false,
  cert_id: "",
  stock_id: "",
  price_sort: "",
  type: 2,
  size_from: [],
  size_to: [],
  size_range: [],
};
